[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[build.env]
NIXPACKS_NODE_VERSION = "20"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "on_failure"

[deploy.env]
PORT = "4173"
