ALTER TABLE "Account"
    ADD COLUMN IF NOT EXISTS "stockBrokerFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS "stockLevyFeePercent" DOUBLE PRECISION NOT NULL DEFAULT 0;
